version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tsec
    versions:
    - 0.1.2
    - 0.1.3
  - dependency-name: gulp-filter
    versions:
    - 6.0.0
  - dependency-name: node-pty
    versions:
    - 0.10.0
  - dependency-name: stringstream
    versions:
    - 0.0.6
  - dependency-name: sshpk
    versions:
    - 1.16.1
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: macaddress
    versions:
    - 0.2.9
  - dependency-name: lodash.template
    versions:
    - 4.5.0
  - dependency-name: lodash
    versions:
    - 4.17.15
  - dependency-name: is-my-json-valid
    versions:
    - 2.20.0
  - dependency-name: gulp
    versions:
    - 4.0.2
  - dependency-name: extend
    versions:
    - 3.0.2
  - dependency-name: concat-with-sourcemaps
    versions:
    - 1.1.0
